# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
#   - repo: https://github.com/Lucas-C/pre-commit-hooks-java
#     rev: "1.3.10"
#     hooks:
#       - id: validate-html

#   - repo: https://github.com/pre-commit/mirrors-prettier
#     rev: "v2.6.0" # Use the sha / tag you want to point at
#     hooks:
#       - id: prettier

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-ast
      - id: check-added-large-files
      - id: check-case-conflict
    #   - id: pretty-format-json
